name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          
      - name: install dependencies
        run: npm install
        
      - name: build
        run: npm run build
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSh_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules, !ormconfig.json !docker-compose.yml"
          target: "~/app/RentxAPI"
          
      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSh_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/RentxAPI
            npm i
            ./node_modules/.bin/typeorm migration:run
            pm2 restart rentx_api
